# Generated by Django 5.0.2 on 2025-08-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.CharField(choices=[('stage1', 'Stage 1 - Foundational Pillars'), ('stage2', 'Stage 2 - Conversion Content (Reviews & Buying Guides)'), ('stage3', 'Stage 3 - Supporting Content (Topic Clusters)'), ('stage4', 'Stage 4 - Authority & Community Content'), ('stage5', 'Stage 5 - Ecosystem Expansion & Monetization'), ('stage6', 'Stage 6 - Advanced Funnel & Brand Building')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('word_count_min', models.IntegerField(default=2000)),
                ('word_count_target', models.IntegerField(default=2500)),
                ('focus_keywords', models.TextField(help_text='Common focus areas for this stage')),
                ('content_style', models.TextField(help_text='Writing style guidelines')),
                ('monetization_focus', models.CharField(default='affiliate', max_length=50)),
                ('system_prompt', models.TextField(help_text='Custom Claude prompt for this stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['stage_id'],
            },
        ),
        migrations.CreateModel(
            name='LinkingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_link_enabled', models.BooleanField(default=True)),
                ('max_internal_links', models.IntegerField(default=5, help_text='Max internal links per post')),
                ('min_words_between_links', models.IntegerField(default=150)),
                ('link_to_newer_posts', models.BooleanField(default=False, help_text='Allow linking to newer posts')),
                ('prefer_same_category', models.BooleanField(default=True)),
                ('auto_create_rules', models.BooleanField(default=True, help_text='Auto-create linking rules from posts')),
                ('use_exact_title', models.BooleanField(default=False)),
                ('vary_anchor_text', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('topic', models.CharField(db_index=True, max_length=200)),
                ('prompt', models.TextField(blank=True)),
                ('affiliate_links', models.TextField(blank=True, help_text='One link per line')),
                ('content', models.TextField()),
                ('edited_content', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Extracted keywords for matching')),
                ('internal_links', models.JSONField(blank=True, default=dict)),
                ('link_to_this_count', models.IntegerField(default=0)),
                ('main_category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('wordpress_post_id', models.CharField(blank=True, max_length=50)),
                ('wordpress_url', models.URLField(blank=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preview', 'Preview'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('focus_keyword', models.CharField(blank=True, db_index=True, max_length=100)),
                ('content_stage', models.CharField(choices=[('stage1', 'Stage 1 - Foundational Pillars'), ('stage2', 'Stage 2 - Conversion Content (Reviews & Buying Guides)'), ('stage3', 'Stage 3 - Supporting Content (Topic Clusters)'), ('stage4', 'Stage 4 - Authority & Community Content'), ('stage5', 'Stage 5 - Ecosystem Expansion & Monetization'), ('stage6', 'Stage 6 - Advanced Funnel & Brand Building')], default='stage1', help_text='Content stage this post belongs to', max_length=10)),
                ('pillar_post', models.BooleanField(default=False, help_text='Is this a pillar post?')),
                ('conversion_focused', models.BooleanField(default=False)),
                ('community_engagement_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('wordpress_media_id', models.CharField(blank=True, max_length=50)),
                ('wordpress_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publisher.publishedpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserContentStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('stage1', 'Stage 1 - Foundational Pillars'), ('stage2', 'Stage 2 - Conversion Content (Reviews & Buying Guides)'), ('stage3', 'Stage 3 - Supporting Content (Topic Clusters)'), ('stage4', 'Stage 4 - Authority & Community Content'), ('stage5', 'Stage 5 - Ecosystem Expansion & Monetization'), ('stage6', 'Stage 6 - Advanced Funnel & Brand Building')], default='stage1', max_length=10)),
                ('stage1_posts', models.IntegerField(default=0)),
                ('stage2_posts', models.IntegerField(default=0)),
                ('stage3_posts', models.IntegerField(default=0)),
                ('stage4_posts', models.IntegerField(default=0)),
                ('stage5_posts', models.IntegerField(default=0)),
                ('stage6_posts', models.IntegerField(default=0)),
                ('primary_niche', models.CharField(blank=True, max_length=100)),
                ('target_audience', models.TextField(blank=True)),
                ('preferred_tone', models.CharField(default='authoritative_friendly', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordPressSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='WordPress site URL (e.g., https://example.com)')),
                ('username', models.CharField(max_length=100)),
                ('app_password', models.CharField(help_text='WordPress application password', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordpress_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'url')},
            },
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='wordpress_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.wordpresssite'),
        ),
        migrations.CreateModel(
            name='InternalLinkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100)),
                ('priority', models.IntegerField(default=1, help_text='Higher priority links are used first')),
                ('max_usage', models.IntegerField(default=3, help_text='Max times to use this link per post')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_rules', to='publisher.publishedpost')),
            ],
            options={
                'ordering': ['-priority', 'keyword'],
                'unique_together': {('user', 'keyword', 'target_post')},
            },
        ),
        migrations.AddIndex(
            model_name='publishedpost',
            index=models.Index(fields=['user', 'status', '-published_at'], name='publisher_p_user_id_3b5669_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedpost',
            index=models.Index(fields=['topic', 'main_category'], name='publisher_p_topic_1f026d_idx'),
        ),
    ]
