# Generated by Django 5.0.2 on 2025-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['is_featured', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='SEO-friendly alt text', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Image caption'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Use as featured image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
